name: Laravel Package Test Action
description: GitHub Action to test Laravel package and library compatibility using PHPUnit
author: Muhammad Zamroni
branding:
  icon: umbrella
  color: orange

inputs:
  operating_system:
    description: The Operating System where the test runs
    required: false
    default: ubuntu-latest
  php_version:
    description: The PHP version where the test runs
    required: false
    default: "8.2"
  php_extensions:
    description: The PHP extension enabled for the test, separated by comma
    required: false
  laravel_version:
    description: The Laravel framework version where the test runs
    required: false
    default: "^11.0"
  branch:
    description: The branch name, tag name, or git reference checksum to check out
    required: false
  laravel_install_args:
    description: The arguments passed to Composer when installing Laravel framework
    required: false
    default: --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-plugins
  package_install_args:
    description: The arguments passed to Composer when installing the package
    required: false
    default: --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-plugins
  phpunit_args:
    description: The arguments passed to PHPUnit when running the test
    required: false
  shell_name:
    description: The shell name used to run the test
    required: false
    default: bash

runs:
  using: composite
  steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}

    - id: setup-php
      name: Setup PHP ${{ inputs.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        extensions: ${{ inputs.php_extensions }}

    - id: check-php-ext
      name: Check PHP Version and Extensions
      shell: ${{ inputs.shell_name }}
      run: php -v && php -m

    - id: cache-composer
      name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ inputs.operating_system }}-php-${{ inputs.php_version }}-laravel-${{ inputs.laravel_version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ inputs.operating_system }}-php-${{ inputs.php_version }}-laravel-${{ inputs.laravel_version }}-
          ${{ inputs.operating_system }}-php-${{ inputs.php_version }}-laravel-
          ${{ inputs.operating_system }}-php-
          ${{ inputs.operating_system }}-

    - id: install-laravel
      name: Install Laravel ${{ inputs.laravel_version }}
      shell: ${{ inputs.shell_name }}
      run: composer require "laravel/framework:${{ inputs.laravel_version }}" ${{ inputs.laravel_install_args }}

    - id: update-package
      name: Update Composer dependencies
      shell: ${{ inputs.shell_name }}
      run: composer update ${{ inputs.package_install_args }}

    - name: Run tests
      shell: ${{ inputs.shell_name }}
      run: vendor/bin/phpunit ${{ inputs.phpunit_args }}
